extension ProvinceName on String {
  String provinceAbbr() {
    switch (this) {
      case 'ATG':
        return 'อ่างทอง';
      case 'AYA':
        return 'พระนครศรีอยุธยา';
      case 'BKK':
        return 'กรุงเทพมหานคร';
      case 'BKN':
        return 'บึงกาฬ';
      case 'BRM':
        return 'บุรีรัมย์';
      case 'CBI':
        return 'ชัยภูมิ';
      case 'CCO':
        return 'ชุมพร';
      case 'CMI':
        return 'เชียงใหม่';
      case 'CNT':
        return 'ชัยนาท';
      case 'CPM':
        return 'ชัยภูมิ';
      case 'CPN':
        return 'ชุมพร';
      case 'CRI':
        return 'เชียงราย';
      case 'CTI':
        return 'ฉะเชิงเทรา';
      case 'KBI':
        return 'กระบี่';
      case 'KKN':
        return 'ขอนแก่น';
      case 'KPT':
        return 'กำแพงเพชร';
      case 'KRI':
        return 'กาญจนบุรี';
      case 'KSN':
        return 'กาฬสินธุ์';
      case 'LEI':
        return 'เลย';
      case 'LPG':
        return 'ลำปาง';
      case 'LPN':
        return 'ลพบุรี';
      case 'LRI':
        return 'ลำพูน';
      case 'MDH':
        return 'แม่ฮ่องสอน';
      case 'MKM':
        return 'มหาสารคาม';
      case 'NAN':
        return 'น่าน';
      case 'NBI':
        return 'นนทบุรี';
      case 'NBP':
        return 'นครพนม';
      case 'NKI':
        return 'นครสวรรค์';
      case 'NMA':
        return 'นครราชสีมา';
      case 'NPM':
        return 'นครปฐม';
      case 'NPT':
        return 'นครปฐม';
      case 'NSN':
        return 'นราธิวาส';
      case 'NST':
        return 'นครศรีธรรมราช';
      case 'NYK':
        return 'นครนายก';
      case 'PBI':
        return 'เพชรบูรณ์';
      case 'PCT':
        return 'พิจิตร';
      case 'PKN':
        return 'ประจวบคีรีขันธ์';
      case 'PKT':
        return 'พังงา';
      case 'PLG':
        return 'พะเยา';
      case 'PLK':
        return 'พิษณุโลก';
      case 'PNB':
        return 'ปทุมธานี';
      case 'PRE':
        return 'ปราจีนบุรี';
      case 'PRI':
        return 'แพร่';
      case 'PTE':
        return 'เพชรบุรี';
      case 'PYO':
        return 'พะเยา';
      case 'RBR':
        return 'ราชบุรี';
      case 'RET':
        return 'ระยอง';
      case 'RYG':
        return 'ระนอง';
      case 'SBR':
        return 'สระบุรี';
      case 'SKA':
        return 'สกลนคร';
      case 'SKM':
        return 'สมุทรสงคราม';
      case 'SKN':
        return 'สมุทรสาคร';
      case 'SKW':
        return 'สมุทรปราการ';
      case 'SNI':
        return 'สิงห์บุรี';
      case 'SNK':
        return 'สระแก้ว';
      case 'SPB':
        return 'สุพรรณบุรี';
      case 'SPK':
        return 'สุโขทัย';
      case 'SRI':
        return 'สุราษฎร์ธานี';
      case 'SRN':
        return 'สุรินทร์';
      case 'SSK':
        return 'ศรีสะเกษ';
      case 'STI':
        return 'สตูล';
      case 'TAK':
        return 'ตาก';
      case 'TRG':
        return 'ตรัง';
      case 'TRT':
        return 'ตราด';
      case 'UBN':
        return 'อุบลราชธานี';
      case 'UDN':
        return 'อุดรธานี';
      case 'UTI':
        return 'อุทัยธานี';
      case 'YLA':
        return 'ยะลา';
      case 'YST':
        return 'ยโสธร';
      default:
        return '';
    }
  }
}